[package]
name = "rustos-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
spin = "0.9.2"
bitflags = "1.2.1"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
